from enum import Enum

class ResponseSignal(Enum):

    FILE_VALIDATED_SUCCESS="FILE_VALIDATED_SUCCESS"
    FILE_TYPE_NOT_SUPORTTED="FILE_TYPE_NOT_SUPORTTED"
    FILE_SIZE_EXCEEDED="FILE_MAX_SIZE_EXCEEDED"
    FILE_UPLOAD_FAILED="FILE_UPLOAD_FAILED"
    FILE_UPLOAD_SUCCESS="FILE_UPLOAD_SUCCESS"