from enum import Enum

class ResponseSignal(Enum):

    FILE_VLAIDATED_SUCCSS="FILE_VLAIDATED_SUCCSS"
    FILE_TYPE_NOT_SUPORTTED="FILE_TYPE_NOT_SUPORTTED"
    FILE_MAX_SIZE_EXCEEDED="FILE_MAX_SIZE_EXCEEDED"
    FILE_UPLOAD_FAILED="FILE_UPLOAD_FAILED"
    FILE_UPLOAD_SUCCESS="FILE_UPLOAD_SUCCESS"