from enum import Enum

class ResponseSignal(Enum):
    
    FILE_TYPE_NOT_SUPPORTED="FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED="FILE_SIZE_EXCEEDED"
    FILE_UPLAOD_SUCCESS="FILE_UPLAOD_SUCCESS"
    FILE_UPLAOD_FAILED="FILE_UPLAOD_FAILED"
    FILE_VALIDATE_SUCCESS='FILE_VALIDATE_SUCCESS'
    
